### ISSUE TITLE
Tom Gilb

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/history-of-testing#125]
### What's wrong?

https://en.wikipedia.org/wiki/Tom_Gilb

missing exact date of birth

Gilb is one of the first to define system and software reliability and the relationship between human error and system error.

**Comment by zaklinica** [comment]
Found birth date - https://www.linkedin.com/in/tomgilb/overlay/contact-info/ 
24.12

**Comment by zaklinica** [comment]
Already added
https://github.com/kiwitcms/history-of-testing/tree/master/December/24/tom_gilb
