### ISSUE TITLE
John Goodenough

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/history-of-testing#126]
### What's wrong?

https://en.wikipedia.org/wiki/John_B._Goodenough

paper published in 1975:

Toward a Theory of Test Data Selection (Goodenough, Gerhart) | The paper by John B. Goodenough and Susan L. Gerhart  discusses formal proof methods and the limitations of structure-based  testing. It also outlines the use of decision tables.

**Comment by zaklinica** [comment]
https://github.com/kiwitcms/history-of-testing/pull/137
