### ISSUE TITLE
A list of software testing people

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#37]
- [ ] Elisabeth Hendrickson, https://testobsessed.com/
- [ ] James Bach, https://www.satisfice.com/about-james-bach, #50 
- [ ] Michael Bolton, https://www.developsense.com/index.html
- [ ] Lisa Crispin, https://lisacrispin.com/
- [ ] Janet Gregory, https://janetgregory.ca/
- [ ] Bas Dijkstra, https://www.ontestautomation.com/about/
- [ ] Alan Richardson, https://www.eviltester.com/
- [ ] Daniel North, https://dannorth.net/about/
- [ ] Mark Fewster
- [ ] Gojko Adzic, https://gojko.net/about/, #49 
- [ ] Joe Colantonio, https://testguild.com/
- [ ] Simon Stewart
- [ ] Angie Jones, https://angiejones.tech/

**Comment by atodorov** [comment]
Split into multiple issues, one per person. Closing.
