### ISSUE TITLE
Dave Gelperin

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/history-of-testing#43]
https://en.wikipedia.org/wiki/Dave_Gelperin

cc @zaklinica

**Comment by zaklinica** [comment]
https://www.techwell.com/users/david-gelperin

https://www.techwell.com/sites/default/files/styles/medium/public/pictures/ClearSpecs.jpg

**Missing the date of birth**

**Comment by atodorov** [comment]
@zaklinica it looks like he had passed away recently:
https://www.hodroffepsteinmemorialchapels.com/obituaries/David-Gelperin/

However the obituary contains the date of birth. Because it is very soon we should make a priority to have this artifact merged before Jan 26th (so we can see the social bot in action).

**Comment by atodorov** [comment]
A bigger image is https://images-na.ssl-images-amazon.com/images/I/A1BXdmEWlEL._SX450_.jpg (will need adjustment)

from https://www.amazon.com/David-Gelperin/e/B0765MCWPM
