### ISSUE TITLE
Mark Harman

### ISSUE THREAD

**Issue by atodorov** [kiwitcms/history-of-testing#44]
https://en.wikipedia.org/wiki/Mark_Harman_(computer_scientist)

cc @zaklinica

**Comment by zaklinica** [comment]
https://engineering.fb.com/2020/09/21/developer-tools/mark-harman-fellow/

picture: https://engineering.fb.com/wp-content/uploads/2020/09/RAeng.jpg

**Missing the date of birth**

**Comment by atodorov** [comment]
https://www.howold.co/person/mark-harman -> June 30, 1964
