### ISSUE TITLE
Elaine Weyuker

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#79]
### What's wrong?

https://scholar.google.com/citations?user=xXjQoLIAAAAJ&hl=en

https://www.cs.ucf.edu/person/elaine-weyuker/

**missing birth date**

**Comment by atodorov** [comment]
https://en.wikipedia.org/wiki/Elaine_Weyuker

https://www.howold.co/person/elaine-weyuker#google_vignette - puts birthday at November 22, 1945 and the education & awards seems to match the same person.
