### ISSUE TITLE
Mark Harman

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#80]
### What's wrong?

https://en.wikipedia.org/wiki/Mark_Harman_(computer_scientist)

https://scholar.google.com/citations?hl=en&user=IwSN8IgAAAAJ

http://www0.cs.ucl.ac.uk/staff/mharman/

https://www.computer.org/profiles/mark-harman

**missing birth date**

**Comment by atodorov** [comment]
Duplicate of #44
