### ISSUE TITLE
William Sealy Gosset

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#95]
### What's wrong?

William is a statistician, who in implicit way has affected A/B testing, but altering the Z-test to create Student's t-test. The t-test can be used to determine if the means of two sets of data are significantly different from each other. So, there is a link, but it is indirect. 
@atodorov , do you think we should add William?

https://en.wikipedia.org/wiki/William_Sealy_Gosset

https://en.wikipedia.org/wiki/Student%27s_t-test

**Comment by atodorov** [comment]
It looks like this has to do with statistical hypothesis / statistical analysis rather than software/hardware testing. For now I think this does not belong to the database.
