### ISSUE TITLE
Paul C. Jorgensen

### ISSUE THREAD

**Issue by zaklinica** [kiwitcms/history-of-testing#99]
### What's wrong?

Missing birth date

There is info, as well as pictures - https://www.amazon.com/Paul-C.-Jorgensen/e/B00C42N3X8%3Fref=dbs_a_mng_rwt_scns_share

**Comment by atodorov** [comment]
https://prabook.com/web/paul_c.jorgensen/1660534 - puts birthday at May 27, 1942  and education matches. The Amazon description looks to be slightly incorrect or maybe family expended over time.

The section About The Author, from https://books.google.bg/books?id=UhTSBQAAQBAJ&printsec=frontcover&dq=inauthor:%22Paul+C.+Jorgensen%22&hl=en&sa=X&redir_esc=y#v=onepage&q&f=false matches the family description so we can conclude it is the same person and we can consider the birth day to be correct!
